/**
 * lb-test
 * JS
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: julian.cuni@microservices.al
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Omit<Role, \'id\'>, schemaOptions: { title: \'NewRole\', exclude: [ \'id\' ] })
 */
export interface NewRole { 
    role: string;
    desc?: string;
}

