/**
 * lb-test
 * JS
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: julian.cuni@microservices.al
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleIncludeFilterItems } from './roleIncludeFilterItems';


export interface RoleFilter { 
    offset?: number;
    limit?: number;
    skip?: number;
    order?: string | Array<string>;
    fields?: object | Set<string>;
    include?: Array<RoleIncludeFilterItems | string>;
}

